[workspace]
members = [
    "crates/*",
    "api",
    "scrapers/*",
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }