/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exchanges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /exchanges - List all available exchanges/DEXes
         * @description Returns a list of exchange identifiers that have pools in the database.
         *     If the database is empty, returns a hardcoded list of supported exchanges.
         */
        get: operations["list_exchanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /pools/refresh - Refresh all pools from TAPP
         * @description This endpoint fetches pool data from TAPP Exchange and updates the database.
         *
         *     NOTE: This implementation requires pool data from TAPP's API or SDK.
         *     The TypeScript implementation uses @tapp-exchange/sdk which provides:
         *     - Pool list with pagination and sorting
         *     - TVL, volume, APR data
         *     - Token pair information
         *
         *     For Rust implementation, options include:
         *     1. Use TAPP's HTTP API (if publicly documented)
         *     2. Fetch pool metadata from on-chain resources
         *     3. Use a proxy service that wraps the TAPP SDK
         *
         *     Current implementation is a PLACEHOLDER showing the expected structure.
         */
        post: operations["refresh_pools"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_pool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pools/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /pools/:id/refresh - Refresh a single pool
         * @description This endpoint fetches the latest data for a specific pool from TAPP.
         */
        post: operations["refresh_single_pool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/refresh/{pool_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /positions/refresh/:pool_id - Refresh positions for a specific pool
         * @description This endpoint fetches position data from the blockchain for a given pool
         *     and updates the database. It intelligently fetches only new positions
         *     if the pool has been synced before, or all positions if it's the first sync.
         */
        post: operations["refresh_positions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /tokens - List all tokens */
        get: operations["list_tokens"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST /tokens/refresh - Refresh token list from TAPP API */
        post: operations["refresh_tokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Model: {
            /** Format: double */
            bonus_apr: number;
            dex: string;
            fee: string;
            id: string;
            /** Format: int32 */
            position_index?: number | null;
            token_a?: string | null;
            token_b?: string | null;
            /** Format: double */
            trading_apr: number;
            /** Format: double */
            tvl: number;
            /** Format: date-time */
            updated_at?: string | null;
            /** Format: double */
            volume_day: number;
            /** Format: double */
            volume_month: number;
            /** Format: double */
            volume_prev_day: number;
            /** Format: double */
            volume_week: number;
        };
        PoolsResponse: {
            count: number;
            pools: components["schemas"]["Model"][];
        };
        RefreshPoolsResponse: {
            message: string;
            pools_updated: number;
            status: string;
        };
        RefreshPositionsResponse: {
            message: string;
            positions_updated: number;
            status: string;
        };
        RefreshResponse: {
            message: string;
            status: string;
            tokens_updated: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_chains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    get_chain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    list_exchanges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of exchanges */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_pools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pools fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolsResponse"];
                };
            };
        };
    };
    refresh_pools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pools refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshPoolsResponse"];
                };
            };
        };
    };
    get_pool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_single_pool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool ID to refresh */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pool refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_positions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pool ID to refresh positions for */
                pool_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positions refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshPositionsResponse"];
                };
            };
            /** @description Pool not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh_tokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResponse"];
                };
            };
        };
    };
}
