//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "positions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub index: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pool: String,
    pub updated_at: Option<DateTime>,
    pub tick_lower: i64,
    pub tick_upper: i64,
    pub liquidity: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pools::Entity",
        from = "Column::Pool",
        to = "super::pools::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pools,
}

impl Related<super::pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
